/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIL;

/**
 *
 * @author ASUS
 */
public class inventory extends javax.swing.JFrame {

    /**
     * Creates new form inventory
     */
    public inventory() {
        initComponents();
        
        readymade_product_type_tb.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        product_type_group = new javax.swing.ButtonGroup();
        inventory_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        product_id_txt = new javax.swing.JTextField();
        selling_price_txt = new javax.swing.JTextField();
        product_name_txt = new javax.swing.JTextField();
        pack_size_txt = new javax.swing.JTextField();
        product_category_cmb = new javax.swing.JComboBox();
        product_unit_cmb = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        assembled_product_type_tb = new javax.swing.JToggleButton();
        readymade_product_type_tb = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        component_product_type_tb = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        inventory_id_txt = new javax.swing.JTextField();
        bin_location_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        min_stock_txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        max_stock_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        add_product_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(140, 50, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventory_panel.setBackground(new java.awt.Color(255, 255, 255));
        inventory_panel.setPreferredSize(new java.awt.Dimension(1300, 720));
        inventory_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ready-made Product");
        inventory_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        product_id_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        product_id_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        inventory_panel.add(product_id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 230, 30));

        selling_price_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        selling_price_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        inventory_panel.add(selling_price_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 230, 30));

        product_name_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        product_name_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        inventory_panel.add(product_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 230, 30));

        pack_size_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pack_size_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        inventory_panel.add(pack_size_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 230, 30));

        product_category_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        inventory_panel.add(product_category_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 220, 30));

        product_unit_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        inventory_panel.add(product_unit_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 220, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Inventory");
        inventory_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Product ID :");
        inventory_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Product Name :");
        inventory_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Pack Size :");
        inventory_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Selling Price :");
        inventory_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Unit of Measure :");
        inventory_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Product Category :");
        inventory_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        product_type_group.add(assembled_product_type_tb);
        assembled_product_type_tb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/toggle_off.png"))); // NOI18N
        assembled_product_type_tb.setContentAreaFilled(false);
        assembled_product_type_tb.setRolloverEnabled(false);
        assembled_product_type_tb.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/toggle_on.png"))); // NOI18N
        assembled_product_type_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assembled_product_type_tbActionPerformed(evt);
            }
        });
        inventory_panel.add(assembled_product_type_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 40, -1));

        product_type_group.add(readymade_product_type_tb);
        readymade_product_type_tb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/toggle_off.png"))); // NOI18N
        readymade_product_type_tb.setContentAreaFilled(false);
        readymade_product_type_tb.setRolloverEnabled(false);
        readymade_product_type_tb.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/toggle_on.png"))); // NOI18N
        readymade_product_type_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readymade_product_type_tbActionPerformed(evt);
            }
        });
        inventory_panel.add(readymade_product_type_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 40, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Product Type :");
        inventory_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Assembled Product");
        inventory_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Component Product");
        inventory_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        product_type_group.add(component_product_type_tb);
        component_product_type_tb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/toggle_off.png"))); // NOI18N
        component_product_type_tb.setContentAreaFilled(false);
        component_product_type_tb.setRolloverEnabled(false);
        component_product_type_tb.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/toggle_on.png"))); // NOI18N
        component_product_type_tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                component_product_type_tbActionPerformed(evt);
            }
        });
        inventory_panel.add(component_product_type_tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 40, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Inventory ID :");
        inventory_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        inventory_id_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inventory_id_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        inventory_panel.add(inventory_id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 230, 30));

        bin_location_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bin_location_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        inventory_panel.add(bin_location_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 230, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Bin Location :");
        inventory_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        min_stock_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        min_stock_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        inventory_panel.add(min_stock_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 230, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Min. Stock Level :");
        inventory_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        max_stock_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        max_stock_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        inventory_panel.add(max_stock_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 230, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Max. Stocl Level :");
        inventory_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        add_product_btn.setText("Save Product");
        inventory_panel.add(add_product_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, -1));

        getContentPane().add(inventory_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assembled_product_type_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assembled_product_type_tbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assembled_product_type_tbActionPerformed

    private void readymade_product_type_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readymade_product_type_tbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readymade_product_type_tbActionPerformed

    private void component_product_type_tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_component_product_type_tbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_component_product_type_tbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_product_btn;
    private javax.swing.JToggleButton assembled_product_type_tb;
    private javax.swing.JTextField bin_location_txt;
    private javax.swing.JToggleButton component_product_type_tb;
    private javax.swing.JTextField inventory_id_txt;
    private javax.swing.JPanel inventory_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField max_stock_txt;
    private javax.swing.JTextField min_stock_txt;
    private javax.swing.JTextField pack_size_txt;
    private javax.swing.JComboBox product_category_cmb;
    private javax.swing.JTextField product_id_txt;
    private javax.swing.JTextField product_name_txt;
    private javax.swing.ButtonGroup product_type_group;
    private javax.swing.JComboBox product_unit_cmb;
    private javax.swing.JToggleButton readymade_product_type_tb;
    private javax.swing.JTextField selling_price_txt;
    // End of variables declaration//GEN-END:variables
}
