/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIL;

import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author ASUS
 */
public class notification_popup extends javax.swing.JFrame {

    /**
     * Creates new form notification_popup
     */
    public notification_popup() {
        initComponents();
        //playSound();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        popup_logo = new javax.swing.JLabel();
        noti_header_lbl = new javax.swing.JLabel();
        noti_des_lbl = new javax.swing.JLabel();
        close_noti_popup_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(1000, 630, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        popup_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notifications_popup_logo.png"))); // NOI18N
        jPanel1.add(popup_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        noti_header_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        noti_header_lbl.setText("Notification Header");
        jPanel1.add(noti_header_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, -1));

        noti_des_lbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        noti_des_lbl.setText("This is a test noti to show the look abcdefghija.");
        noti_des_lbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(noti_des_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 250, 40));

        close_noti_popup_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noti_pop_close_btn.png"))); // NOI18N
        close_noti_popup_btn.setContentAreaFilled(false);
        close_noti_popup_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noti_pop_close_btn_hover.png"))); // NOI18N
        close_noti_popup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_noti_popup_btnActionPerformed(evt);
            }
        });
        jPanel1.add(close_noti_popup_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 5, 15, 15));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 93));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_noti_popup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_noti_popup_btnActionPerformed
        
        this.dispose();
        System.gc();
        
    }//GEN-LAST:event_close_noti_popup_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notification_popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notification_popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notification_popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notification_popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notification_popup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_noti_popup_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel noti_des_lbl;
    private javax.swing.JLabel noti_header_lbl;
    private javax.swing.JLabel popup_logo;
    // End of variables declaration//GEN-END:variables

    
public void playSound() {
  
   File audio = new File("D:\\noti_tone.wav");
   
        try {
            
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(audio));
            clip.start();
            
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        
}   

public  void message(String headin){



}

}
