/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIL;

import com.harshadura.gsm.smsdura.GsmModem;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.security.SecureRandom;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class password_recover extends javax.swing.JFrame {

    String formatted;
    String username;
    option_pane op=new option_pane();
    
    public password_recover() {
        initComponents();
        new_pass_pw.setEnabled(false);
        confirm_new_pass_pw.setEnabled(false);
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username_txt = new javax.swing.JTextField();
        password_lbl = new javax.swing.JLabel();
        change_pass_btn = new javax.swing.JButton();
        new_pass_pw = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pass_recover_close_btn = new javax.swing.JButton();
        verification_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        password_lbl1 = new javax.swing.JLabel();
        confirm_new_pass_pw = new javax.swing.JPasswordField();
        loyalty_discount_icon_lbl = new javax.swing.JLabel();
        send_code_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(520, 330));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        username_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        username_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_txtActionPerformed(evt);
            }
        });
        username_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                username_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                username_txtKeyTyped(evt);
            }
        });
        jPanel1.add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 230, 30));

        password_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password_lbl.setText("New Password :");
        jPanel1.add(password_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        change_pass_btn.setBackground(new java.awt.Color(34, 155, 60));
        change_pass_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        change_pass_btn.setForeground(new java.awt.Color(255, 255, 255));
        change_pass_btn.setText("Change");
        change_pass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_pass_btnActionPerformed(evt);
            }
        });
        jPanel1.add(change_pass_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 270, 130, -1));

        new_pass_pw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        new_pass_pw.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        new_pass_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_pass_pwActionPerformed(evt);
            }
        });
        jPanel1.add(new_pass_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Username :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password Recovery");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, 170, -1));

        pass_recover_close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sub_close_btn.png"))); // NOI18N
        pass_recover_close_btn.setContentAreaFilled(false);
        pass_recover_close_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sub_close_btn_hover.png"))); // NOI18N
        pass_recover_close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_recover_close_btnActionPerformed(evt);
            }
        });
        jPanel2.add(pass_recover_close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 50));

        verification_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        verification_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        verification_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verification_txtActionPerformed(evt);
            }
        });
        verification_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                verification_txtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verification_txtKeyTyped(evt);
            }
        });
        jPanel1.add(verification_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 230, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Verification Code :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        password_lbl1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password_lbl1.setText("Confirm New Password :");
        jPanel1.add(password_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        confirm_new_pass_pw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        confirm_new_pass_pw.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        confirm_new_pass_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_new_pass_pwActionPerformed(evt);
            }
        });
        jPanel1.add(confirm_new_pass_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 230, 30));

        loyalty_discount_icon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loyalty_discount_icon.png"))); // NOI18N
        jPanel1.add(loyalty_discount_icon_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 391, 40, 30));

        send_code_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/green_tick.png"))); // NOI18N
        send_code_btn.setContentAreaFilled(false);
        send_code_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_code_btnActionPerformed(evt);
            }
        });
        jPanel1.add(send_code_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 30, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/green_tick.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pass_recover_close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_recover_close_btnActionPerformed

        this.dispose();
        System.gc();
    }//GEN-LAST:event_pass_recover_close_btnActionPerformed

    private void username_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyTyped

        

    }//GEN-LAST:event_username_txtKeyTyped

    private void username_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_txtActionPerformed

    private void verification_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verification_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verification_txtActionPerformed

    private void verification_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verification_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_verification_txtKeyTyped

    private void new_pass_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_pass_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_pass_pwActionPerformed

    private void confirm_new_pass_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_new_pass_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_new_pass_pwActionPerformed

    private void change_pass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_pass_btnActionPerformed
      
        
        String new_pass = new String(confirm_new_pass_pw.getText());
        String new_pass_con = new String(new_pass_pw.getText());
        
        if(new_pass.equals(new_pass_con)){
        
            
            try {
                System.out.println(username);
                System.out.println(new_pass_con);
             ConnDB.iud("update users SET password='"+new_pass_con+"' where username='"+username+"'");
            
            
             op.setVisible(true);
           op.message("password updated successfully");
            
        } catch (Exception e) {
   
            e.printStackTrace();
        
        }
            
        
        }
        
        else{
           op.setVisible(true);
           op.message("password not match");
        
        
        }
        
        
    }//GEN-LAST:event_change_pass_btnActionPerformed

    private void username_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyReleased
        
        
        
    }//GEN-LAST:event_username_txtKeyReleased

    private void username_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyPressed
        
        
        
    }//GEN-LAST:event_username_txtKeyPressed

    private void verification_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verification_txtKeyPressed
        
      
        
    }//GEN-LAST:event_verification_txtKeyPressed

    private void send_code_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_code_btnActionPerformed
       
        username = username_txt.getText();
        
        
        
        try {
            
            ResultSet rs = ConnDB.search("select * from users where username = '"+username+"'");
            
            while(rs.next()){
            
                String username_db = rs.getString("username");
                String mobile = rs.getString("mobile_number");
                
                if(username_db.equals(username)){
                    
                    
                    verification_txt.setEnabled(true);
                    
                    SecureRandom random = new SecureRandom();
                    int num = random.nextInt(100000);
                    formatted = String.format("%05d", num); 
                    System.out.println(formatted);
                    
                    
                    String port = "COM6"; //Modem Port.
                    int bitRate = 115200; //this is also optional. leave as it is.
                    String modemName = "ZTE"; //this is optional.
                    String modemPin = "0000"; //Pin code if any have assigned to the modem.
                    String SMSC = "+9477000003"; //Message Center Number ex. Mobitel

   
                    GsmModem gsmModem = new GsmModem();
                    GsmModem.configModem(port, bitRate, modemName, modemPin, SMSC);
                    gsmModem.Sender(mobile, "Your Verification Code is : "+formatted); // (tp, msg)
                    
                    
    
                
                }
                
                else{
                
                    System.out.println("wrong");
                
                }
            
            }
            
        } catch (Exception e) {
            
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_send_code_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String veri = verification_txt.getText();
    
       if(veri.equals(formatted)){
       
           new_pass_pw.setEnabled(true);
        confirm_new_pass_pw.setEnabled(true);
       
       }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(password_recover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(password_recover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(password_recover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(password_recover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new password_recover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change_pass_btn;
    private javax.swing.JPasswordField confirm_new_pass_pw;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loyalty_discount_icon_lbl;
    private javax.swing.JPasswordField new_pass_pw;
    private javax.swing.JButton pass_recover_close_btn;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JLabel password_lbl1;
    private javax.swing.JButton send_code_btn;
    private javax.swing.JTextField username_txt;
    private javax.swing.JTextField verification_txt;
    // End of variables declaration//GEN-END:variables
}
