/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIL;

/**
 *
 * @author ASUS
 */
public class purchase extends javax.swing.JFrame {

    /**
     * Creates new form purchase
     */
    public purchase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pro_name_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_list_table = new javax.swing.JTable();
        supplier_id_txt = new javax.swing.JTextField();
        supplier_name_txt = new javax.swing.JTextField();
        pu_orenr_Id = new javax.swing.JTextField();
        save_and_print_btn = new javax.swing.JButton();
        complete_invoice_btn = new javax.swing.JButton();
        unit_price_lbl = new javax.swing.JLabel();
        total_lbl = new javax.swing.JLabel();
        sub_total_lbl = new javax.swing.JLabel();
        qty_lbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        qty_txt = new javax.swing.JTextField();
        search_purchase_order_btn = new javax.swing.JButton();
        search_supplier_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(140, 50, 0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1230, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Purchase");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Purchase Order ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Purchase order ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Supplier Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Supplier ID :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Product Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Unit Price :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Quantity : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Sub Total :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Total : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, -1, -1));

        pro_name_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(pro_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 230, 30));

        product_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Code", "Product Name", "Unit Price", "Quantity", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(product_list_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 1100, 180));

        supplier_id_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(supplier_id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 230, 30));

        supplier_name_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(supplier_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 230, 30));

        pu_orenr_Id.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(pu_orenr_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 30));

        save_and_print_btn.setBackground(new java.awt.Color(34, 155, 60));
        save_and_print_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save_and_print_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_and_print_btn.setText("Save & Print");
        jPanel1.add(save_and_print_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, -1, -1));

        complete_invoice_btn.setBackground(new java.awt.Color(34, 155, 60));
        complete_invoice_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        complete_invoice_btn.setForeground(new java.awt.Color(255, 255, 255));
        complete_invoice_btn.setText("Complete");
        complete_invoice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_invoice_btnActionPerformed(evt);
            }
        });
        jPanel1.add(complete_invoice_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, -1, -1));

        unit_price_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        unit_price_lbl.setText("Unit_Price");
        jPanel1.add(unit_price_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 90, -1));

        total_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        total_lbl.setText("total");
        jPanel1.add(total_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 600, 70, -1));

        sub_total_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sub_total_lbl.setText("sub_total");
        jPanel1.add(sub_total_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 90, -1));

        qty_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qty_lbl.setText("quantity");
        jPanel1.add(qty_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Quantity :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        qty_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(qty_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 230, 30));

        search_purchase_order_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        search_purchase_order_btn.setContentAreaFilled(false);
        search_purchase_order_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon_hover.png"))); // NOI18N
        jPanel1.add(search_purchase_order_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 30, 30));

        search_supplier_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        search_supplier_btn.setContentAreaFilled(false);
        search_supplier_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon_hover.png"))); // NOI18N
        jPanel1.add(search_supplier_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void complete_invoice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_invoice_btnActionPerformed

       

        String purchaseId= pu_orenr_Id.getText();
        String purchaseCode= supplier_name_txt.getText();
        String purchaseCodeID = supplier_name_txt.getText();
        String productName= pro_name_txt.getText();
        int qty01=Integer.parseInt(qty_txt.getText());
        
        double unitPrice= Double.parseDouble(unit_price_lbl.getText());
        double subTotal= Double.parseDouble(sub_total_lbl.getText());
        int quantity= Integer.parseInt(qty_lbl.getText());
       
        double total= Double.parseDouble(total_lbl.getText());

        

        if (purchaseId.isEmpty()|| purchaseCode.isEmpty() || purchaseCodeID.isEmpty() || productName.isEmpty() || qty_txt.getText().isEmpty() ||  unit_price_lbl.getText().isEmpty() || sub_total_lbl.getText().isEmpty() || qty_lbl.getText().isEmpty() || total_lbl.getText().isEmpty()   ){}

    }//GEN-LAST:event_complete_invoice_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton complete_invoice_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pro_name_txt;
    private javax.swing.JTable product_list_table;
    private javax.swing.JTextField pu_orenr_Id;
    private javax.swing.JLabel qty_lbl;
    private javax.swing.JTextField qty_txt;
    private javax.swing.JButton save_and_print_btn;
    private javax.swing.JButton search_purchase_order_btn;
    private javax.swing.JButton search_supplier_btn;
    private javax.swing.JLabel sub_total_lbl;
    private javax.swing.JTextField supplier_id_txt;
    private javax.swing.JTextField supplier_name_txt;
    private javax.swing.JLabel total_lbl;
    private javax.swing.JLabel unit_price_lbl;
    // End of variables declaration//GEN-END:variables
}
