/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIL;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.naming.spi.DirStateFactory;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class sales extends javax.swing.JFrame {

    view_invoice view_invoice = new view_invoice();
    double qty = 0.0;
    String count;
    boolean loyalty = false;
    double discount;
    option_pane p;
    double discount1;
    
    

    public sales() {
        initComponents();
        
        discount_txt.setText("0");
        jScrollPane2.setVisible(false);
        jList1.setVisible(false);
          product_code_txt.setEnabled(false);
            product_name_txt.setEnabled(false);
            discount_txt.setEnabled(false);
            quantity_txt.setEnabled(false);
            unit_price_txt.setEnabled(false);
            available_txt.setEnabled(false);
            product_code_txt.setEnabled(false);
            complete_invoice_btn.setVisible(false);
            save_and_print_btn.setVisible(false);
            String timeStamp = new SimpleDateFormat("yyyy/MM/dd").format(Calendar.getInstance().getTime());
            invoice_date_txt.setText(timeStamp);
        auto();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        invoice_id_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        loyalty_card_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        customer_name_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        invoice_date_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        product_code_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        available_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        product_list_table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        discount_txt = new javax.swing.JTextField();
        balance_lbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cash_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        quantity_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        gross_amount_lbl = new javax.swing.JLabel();
        net_amount_lbl = new javax.swing.JLabel();
        search_customer_mobile_btn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        product_name_txt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        item_count_lbl = new javax.swing.JLabel();
        save_and_print_btn = new javax.swing.JButton();
        complete_invoice_btn = new javax.swing.JButton();
        search_invoice_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        search_product_btn = new javax.swing.JButton();
        view_invoice_btn = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        add_new_invoice_clear_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        unit_price_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        mobile_txt = new javax.swing.JTextField();
        loyalty_discount_icon_lbl = new javax.swing.JLabel();
        delete_product_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(140, 50, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setText("Sales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Invoice ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        invoice_id_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        invoice_id_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(invoice_id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 230, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Loyalty Card No :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 240, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 230, 60));

        loyalty_card_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loyalty_card_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(loyalty_card_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Customer Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        customer_name_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        customer_name_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(customer_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 230, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Invoice Date :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        invoice_date_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        invoice_date_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(invoice_date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 230, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Product Code :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        product_code_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        product_code_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        product_code_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_code_txtActionPerformed(evt);
            }
        });
        product_code_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                product_code_txtKeyReleased(evt);
            }
        });
        jPanel1.add(product_code_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 230, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Balance :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, -1, -1));

        available_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        available_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(available_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 230, 30));

        product_list_table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        product_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Product Name", "Unit Price", "Quantity", "Discount", "Sub Total"
            }
        ));
        product_list_table.setRowHeight(20);
        jScrollPane1.setViewportView(product_list_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1120, 170));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Availability :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Discount :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        discount_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        discount_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(discount_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 230, 30));

        balance_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        balance_lbl.setText("LKR 0.00");
        jPanel1.add(balance_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Cash :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, -1, -1));

        cash_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cash_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        cash_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash_txtActionPerformed(evt);
            }
        });
        cash_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cash_txtKeyTyped(evt);
            }
        });
        jPanel1.add(cash_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, 230, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Net Amount :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Quantity :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        quantity_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        quantity_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        quantity_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity_txtActionPerformed(evt);
            }
        });
        quantity_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantity_txtKeyReleased(evt);
            }
        });
        jPanel1.add(quantity_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 230, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Gross Amount :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, -1, -1));

        gross_amount_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gross_amount_lbl.setText("LKR 0.00");
        jPanel1.add(gross_amount_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, -1, -1));

        net_amount_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        net_amount_lbl.setText("LKR 0.00");
        jPanel1.add(net_amount_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 680, -1, -1));

        search_customer_mobile_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        search_customer_mobile_btn.setContentAreaFilled(false);
        search_customer_mobile_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon_hover.png"))); // NOI18N
        search_customer_mobile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_customer_mobile_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_customer_mobile_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 30, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Product Name :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 290, -1, -1));

        product_name_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        product_name_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        product_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_name_txtActionPerformed(evt);
            }
        });
        product_name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                product_name_txtKeyReleased(evt);
            }
        });
        jPanel1.add(product_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 230, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Item Count :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, -1, -1));

        item_count_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        item_count_lbl.setText("LKR 0.00");
        jPanel1.add(item_count_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 680, -1, -1));

        save_and_print_btn.setBackground(new java.awt.Color(34, 155, 60));
        save_and_print_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save_and_print_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_and_print_btn.setText("Save & Print");
        jPanel1.add(save_and_print_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 670, -1, -1));

        complete_invoice_btn.setBackground(new java.awt.Color(34, 155, 60));
        complete_invoice_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        complete_invoice_btn.setForeground(new java.awt.Color(255, 255, 255));
        complete_invoice_btn.setText("Complete");
        complete_invoice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_invoice_btnActionPerformed(evt);
            }
        });
        jPanel1.add(complete_invoice_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 670, -1, -1));

        search_invoice_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        search_invoice_btn.setContentAreaFilled(false);
        search_invoice_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon_hover.png"))); // NOI18N
        search_invoice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_invoice_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_invoice_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 30, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Sales Invoice");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        search_product_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        search_product_btn.setContentAreaFilled(false);
        search_product_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon_hover.png"))); // NOI18N
        search_product_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_product_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_product_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 30, 30));

        view_invoice_btn.setBackground(new java.awt.Color(34, 155, 60));
        view_invoice_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        view_invoice_btn.setForeground(new java.awt.Color(255, 255, 255));
        view_invoice_btn.setText("View Invoice");
        view_invoice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_invoice_btnActionPerformed(evt);
            }
        });
        jPanel1.add(view_invoice_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1208, 10));

        add_new_invoice_clear_btn.setBackground(new java.awt.Color(34, 155, 60));
        add_new_invoice_clear_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add_new_invoice_clear_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_new_invoice_clear_btn.setText("New");
        add_new_invoice_clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_invoice_clear_btnActionPerformed(evt);
            }
        });
        jPanel1.add(add_new_invoice_clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Unit Price :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 340, -1, -1));

        unit_price_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(unit_price_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 230, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Mobile No :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 140, -1, -1));

        mobile_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mobile_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        mobile_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_txtActionPerformed(evt);
            }
        });
        jPanel1.add(mobile_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 230, 30));

        loyalty_discount_icon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loyalty_discount_icon.png"))); // NOI18N
        jPanel1.add(loyalty_discount_icon_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 391, 40, 30));

        delete_product_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_icon.png"))); // NOI18N
        delete_product_btn.setToolTipText("Delete Product");
        delete_product_btn.setContentAreaFilled(false);
        delete_product_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_icon_hover.png"))); // NOI18N
        delete_product_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_product_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_product_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void complete_invoice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_invoice_btnActionPerformed


        String invoiceId = invoice_id_txt.getText();
        String customerName = customer_name_txt.getText();
        int loyaltyCardNo = Integer.parseInt(loyalty_card_txt.getText());
        String date = invoice_date_txt.getText();
        String productCode = product_code_txt.getText();
       
        
        double cash = Double.parseDouble(cash_txt.getText());
       

        double grossAmount = Double.parseDouble(gross_amount_lbl.getText());
        double netAmount = Double.parseDouble(net_amount_lbl.getText());
        double balance = Double.parseDouble(balance_lbl.getText());

        double itemCount = Double.parseDouble(item_count_lbl.getText());
      
        String user="op";
        if (invoiceId.isEmpty() || customerName.isEmpty() || loyalty_card_txt.getText().isEmpty() || date.isEmpty() ||  gross_amount_lbl.getText().isEmpty() || net_amount_lbl.getText().isEmpty() || balance_lbl.getText().isEmpty() || item_count_lbl.getText().isEmpty()) {
       
        
        
        
        }else{
            try {
                  ConnDB.iud("insert into invoice values('"+invoiceId+"','"+loyaltyCardNo+"','"+customerName+"','"+date+"','"+grossAmount+"','"+discount1+"','"+netAmount+"','"+cash+"','"+balance+"','"+user+"')");
            
              DefaultTableModel dtm=(DefaultTableModel)product_list_table.getModel();
        double tot=0;
        for(int i= 0;i<dtm.getRowCount();i++){
               String name=dtm.getValueAt(i, 0).toString();
            try {
                String pid=dtm.getValueAt(i, 0).toString();
                 String pname=dtm.getValueAt(i, 1).toString();
                  String punit=dtm.getValueAt(i, 2).toString();
                   String pqty=dtm.getValueAt(i, 3).toString();
                    String psub=dtm.getValueAt(i, 5).toString();
                     String pdis=dtm.getValueAt(i, 4).toString();
                     
                try {
                     ConnDB.iud("insert into invoice_items (invoice_id,product_code,product_name,unit_price,qty,subtotal,discount) values('"+invoice_id_txt.getText()+"',"
                        + "'"+pid+"','"+pname+"','"+punit+"','"+pqty+"','"+psub+"','"+pdis+"') ");
                } catch (Exception e) {
                    e.printStackTrace();
                }
               
             
                 ResultSet rs=ConnDB.search("select * from inventory where product_code='"+name+"'");
                
                 
                 while(rs.next()){
                 double qty2=Double.parseDouble(rs.getString("qty"));
                 
               double invqty=(double) dtm.getValueAt(i,3);
               
                 
                 double invo=qty2-invqty;
                 System.out.println(invo+"");
                 
                 ConnDB.iud("update inventory set qty='"+invo+"' where product_code='"+name+"'");
                 }
                  
            } catch (Exception e) {
                e.printStackTrace();
            }
          
             
             
        }
            
            
            
            
            } catch (Exception e) {
                e.printStackTrace();
            }
      
        
        }


    }//GEN-LAST:event_complete_invoice_btnActionPerformed

    private void view_invoice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_invoice_btnActionPerformed

        view_invoice.setVisible(true);

    }//GEN-LAST:event_view_invoice_btnActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String name1 = jList1.getSelectedValue().toString();
        product_name_txt.setText(jList1.getSelectedValue().toString());
        jList1.setVisible(false);
        jScrollPane2.setVisible(false);

        try {

            ResultSet rs = ConnDB.search("select * from product where product_name like '" + product_name_txt.getText() + "%' and status='active' ");
            Vector v = new Vector();
            while (rs.next()) {
                product_code_txt.setText(rs.getString("product_code"));
                unit_price_txt.setText(rs.getString("selling_price"));

                jList1.setListData(v);

            }

            rs = ConnDB.search("select * from loyality_products where product_code ='" + product_code_txt.getText() + "' ");
            v = new Vector();
            if (rs.next()) {
                discount_txt.setText(rs.getString("discount"));
                count = rs.getString("max_count");
                loyalty_discount_icon_lbl.setVisible(true);
                loyalty = true;
            } else {

                loyalty_discount_icon_lbl.setVisible(false);

            }
            quantity_txt.grabFocus();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void product_name_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_product_name_txtKeyReleased
        try {

            int i = product_name_txt.getText().length();
            if (i == 0) {
                System.out.println("4444");
                jScrollPane2.setVisible(false);
                jList1.setVisible(false);

            } else {
                ResultSet rs = ConnDB.search("select * from product where product_name like '" + product_name_txt.getText() + "%' and status='active' ");
                Vector v = new Vector();
                while (rs.next()) {
                    jScrollPane2.setVisible(true);
                    jList1.setVisible(true);
                    v.add(rs.getString("product_name"));
                    jScrollPane2.setVisible(true);
                    jList1.setVisible(true);

                }
                jList1.setListData(v);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_product_name_txtKeyReleased

    private void product_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_name_txtActionPerformed
        try {
            jScrollPane2.setVisible(false);
            jList1.setVisible(false);
            ResultSet rs = ConnDB.search("select * from product where product_name like '" + product_name_txt.getText() + "%' and status='active' ");
            Vector v = new Vector();
            while (rs.next()) {
                product_code_txt.setText(rs.getString("product_code"));

                jList1.setListData(v);

            }

            rs = ConnDB.search("select * from loyality_products where product_code ='" + product_code_txt.getText() + "' ");
            v = new Vector();
            if (rs.next()) {
                discount_txt.setText(rs.getString("discount"));
                count = rs.getString("max_count");
                loyalty_discount_icon_lbl.setVisible(true);
                loyalty = true;
            } else {

                loyalty_discount_icon_lbl.setVisible(false);

            }

            discount_txt.grabFocus();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        quantity_txt.grabFocus();
    }//GEN-LAST:event_product_name_txtActionPerformed

    private void quantity_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantity_txtKeyReleased

        if (quantity_txt.getText().length() == 0) {

            available_txt.setText((""));

        } else {

            double available = Double.parseDouble(quantity_txt.getText());

            try {

                ResultSet rs = ConnDB.search("select * from inventory where product_code='" + product_code_txt.getText() + "' ");
                Vector v = new Vector();
                while (rs.next()) {
                    available_txt.setText(rs.getString("qty"));
                    double qty = Double.parseDouble(rs.getString("qty"));
                    qty -= available;
                    available_txt.setText((qty + ""));

                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_quantity_txtKeyReleased

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed

    }//GEN-LAST:event_jList1KeyPressed

    private void search_customer_mobile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_customer_mobile_btnActionPerformed
        try {

            ResultSet rs = ConnDB.search("select * from loyality where 	mobile_number='" + mobile_txt.getText() + "' ");
            Vector v = new Vector();
            while (rs.next()) {
                loyalty_card_txt.setText(rs.getString("loyality_card_number"));
                customer_name_txt.setText(rs.getString("customer_name"));

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_search_customer_mobile_btnActionPerformed

    private void mobile_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_txtActionPerformed

        if (mobile_txt.getText().length() == 0) {
            customer_name_txt.setText("cash");
            product_code_txt.setEnabled(true);
            product_name_txt.setEnabled(true);
            discount_txt.setEnabled(true);
            quantity_txt.setEnabled(true);
            unit_price_txt.setEnabled(true);
            available_txt.setEnabled(false);
            product_code_txt.setEnabled(true);
            product_code_txt.grabFocus();
            loyalty_card_txt.setText("0");
        } else {

            product_code_txt.setEnabled(true);
            product_name_txt.setEnabled(true);
            discount_txt.setEnabled(true);
            quantity_txt.setEnabled(true);
            unit_price_txt.setEnabled(true);
            available_txt.setEnabled(false);
            product_code_txt.setEnabled(true);
            product_code_txt.grabFocus();

            try {

                ResultSet rs = ConnDB.search("select * from loyality where mobile_number='" + mobile_txt.getText() + "' ");
                Vector v = new Vector();
                while (rs.next()) {
                    loyalty_card_txt.setText(rs.getString("loyality_card_number"));
                    customer_name_txt.setText(rs.getString("customer_name"));

                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_mobile_txtActionPerformed

    private void search_product_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_product_btnActionPerformed
        try {

            ResultSet rs = ConnDB.search("select * from product where product_code like '" + product_code_txt.getText() + "%' and status='active' ");
            Vector v = new Vector();
            while (rs.next()) {
                product_name_txt.setText(rs.getString("product_name"));
                unit_price_txt.setText(rs.getString("selling_price"));

            }

            rs = ConnDB.search("select * from loyality_products where product_code ='" + product_code_txt.getText() + "' ");
            v = new Vector();
            if (rs.next()) {
                discount_txt.setText(rs.getString("discount"));
                loyalty_discount_icon_lbl.setVisible(true);
                count = rs.getString("max_count");
                loyalty = true;
            } else {

                loyalty_discount_icon_lbl.setVisible(false);

            }
            quantity_txt.grabFocus();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_search_product_btnActionPerformed

    private void add_new_invoice_clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_invoice_clear_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_add_new_invoice_clear_btnActionPerformed

    private void quantity_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity_txtActionPerformed
        
        if(quantity_txt.getText().length()==0){
        
        
        
        }else{
        double discount1 = 0.0;
        if (loyalty) {
            loyalty=false;
            int max = Integer.parseInt(count);
            int buy = Integer.parseInt(quantity_txt.getText());
            if (max < buy) {
                p = new option_pane("Discount Limit Exceeded", "Discount valid for only " + max + " products ");
                p.setVisible(true);
                double dis = Double.parseDouble(discount_txt.getText());
                discount1 = 0.0;
                discount1 = max * dis;
                discount_txt.setText(discount1+"");
            } else {
                discount1 = 0.0;
                double dis = Double.parseDouble(discount_txt.getText());
                double count = Double.parseDouble(quantity_txt.getText());

                discount1 = count * dis;
                discount_txt.setText(discount1+"");

            }

        }else{
        
        discount_txt.setText("0.0");
                
        
        }

        String exsist = "No";
        Vector v = new Vector();
        DefaultTableModel dtm = (DefaultTableModel) product_list_table.getModel();

        for (int i = 0; i < dtm.getRowCount(); ++i) {
            System.out.println("ok");
            if (dtm.getValueAt(i, 1).equals(product_name_txt.getText())) {
                exsist = "yes";
                double m, m2, tot;
                 double dis;
                m = (double) dtm.getValueAt(i, 3);

                m2 = Double.parseDouble(quantity_txt.getText());
                tot = m + m2;

           dis= (double) dtm.getValueAt(i,4);
         
          
          double dis3=Double.parseDouble(discount_txt.getText());
          double dis2=Double.parseDouble(discount_txt.getText());
          dis2+=dis;
                System.out.println(dtm.getValueAt(i,4));
                dtm.setValueAt(tot, i, 3);

                double tot4, tot5, tot6;
                tot4 = (double) dtm.getValueAt(i, 5);
                tot5 = Double.parseDouble(quantity_txt.getText()) * Double.parseDouble(unit_price_txt.getText());
                tot6 = (tot4 + tot5);
               tot6-=dis3;
                dtm.setValueAt(tot6, i, 5);

               dtm.setValueAt(dis2, i, 4);

            }

        }
        
        
        
        if (exsist != "yes" || dtm.getRowCount() == 0) {
             double dis=Double.parseDouble(discount_txt.getText());
            v.add(product_code_txt.getText());
            v.add(product_name_txt.getText());
            v.add(unit_price_txt.getText());

           double r = Double.parseDouble(quantity_txt.getText());
            v.add(r);
            
            double qt=Double.parseDouble(discount_txt.getText());
            v.add(qt);
            
            Double d = Double.parseDouble(quantity_txt.getText()) * Double.parseDouble(unit_price_txt.getText());
           d-=dis;
            
            v.add(d);
            dtm.addRow(v);

        }
        calTot();
        discount_txt.setText(null);
        product_code_txt.setText(null);
        product_name_txt.setText(null);
        discount_txt.setText(null);
        unit_price_txt.setText(null);
        quantity_txt.setText(null);
        discount_txt.setText(null);
        available_txt.setText(null);
        loyalty_discount_icon_lbl.setVisible(false);
        
        product_code_txt.grabFocus();
        }
    }//GEN-LAST:event_quantity_txtActionPerformed

    private void product_code_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_code_txtActionPerformed
        try {

            ResultSet rs = ConnDB.search("select * from product where product_code like '" + product_code_txt.getText() + "%' and status='active' ");
            Vector v = new Vector();
            while (rs.next()) {
                product_name_txt.setText(rs.getString("product_name"));
                unit_price_txt.setText(rs.getString("selling_price"));

            }

            rs = ConnDB.search("select * from loyality_products where product_code ='" + product_code_txt.getText() + "' ");
            v = new Vector();
            if (rs.next()) {
                discount_txt.setText(rs.getString("discount"));
                loyalty_discount_icon_lbl.setVisible(true);
                count = rs.getString("max_count");
                loyalty = true;
            } else {

                loyalty_discount_icon_lbl.setVisible(false);

            }
            quantity_txt.grabFocus();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_product_code_txtActionPerformed

    private void delete_product_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_product_btnActionPerformed
        DefaultTableModel df = (DefaultTableModel) product_list_table.getModel();
        try {
            int selectedIndex = product_list_table.getSelectedRow();
            
            df.removeRow(selectedIndex);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_delete_product_btnActionPerformed

    private void product_code_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_product_code_txtKeyReleased
       if (evt.getKeyCode()==35) {
            cash_txt.grabFocus();
        }
    }//GEN-LAST:event_product_code_txtKeyReleased

    private void cash_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash_txtActionPerformed
      
        if(cash_txt.getText().length()>0){
         double cash=Double.parseDouble(cash_txt.getText());
       double net=Double.parseDouble(net_amount_lbl.getText());
       if(cash>net){
       
       
       double bal=cash-net;
       
       
       
       balance_lbl.setText(bal+"");
        complete_invoice_btn.setVisible(true);
            save_and_print_btn.setVisible(true);
       }else{
           System.out.println("net amount greater than chash");
       
       }
        }
        
       
    }//GEN-LAST:event_cash_txtActionPerformed

    private void cash_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cash_txtKeyTyped
        char t = evt.getKeyChar();
        if (!Character.isDigit(t)) {
            evt.consume();
        }
    }//GEN-LAST:event_cash_txtKeyTyped

    private void search_invoice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_invoice_btnActionPerformed
        try {
          ResultSet rs=ConnDB.search("select * from invoice where invoice_id='"+invoice_id_txt.getText()+"'");
          
          
          if(rs.next()){
          
          invoice_date_txt.setText(rs.getString("invoice_date"));
          loyalty_card_txt.setText(rs.getString("loyality_card_number"));
          customer_name_txt.setText(rs.getString("customer_name"));
          
          
          
          }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_search_invoice_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_new_invoice_clear_btn;
    private javax.swing.JTextField available_txt;
    private javax.swing.JLabel balance_lbl;
    private javax.swing.JTextField cash_txt;
    private javax.swing.JButton complete_invoice_btn;
    private javax.swing.JTextField customer_name_txt;
    private javax.swing.JButton delete_product_btn;
    private javax.swing.JTextField discount_txt;
    private javax.swing.JLabel gross_amount_lbl;
    private javax.swing.JTextField invoice_date_txt;
    private javax.swing.JTextField invoice_id_txt;
    private javax.swing.JLabel item_count_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField loyalty_card_txt;
    private javax.swing.JLabel loyalty_discount_icon_lbl;
    private javax.swing.JTextField mobile_txt;
    private javax.swing.JLabel net_amount_lbl;
    private javax.swing.JTextField product_code_txt;
    private javax.swing.JTable product_list_table;
    private javax.swing.JTextField product_name_txt;
    private javax.swing.JTextField quantity_txt;
    private javax.swing.JButton save_and_print_btn;
    private javax.swing.JButton search_customer_mobile_btn;
    private javax.swing.JButton search_invoice_btn;
    private javax.swing.JButton search_product_btn;
    private javax.swing.JTextField unit_price_txt;
    private javax.swing.JButton view_invoice_btn;
    // End of variables declaration//GEN-END:variables

    private void auto() {

        try {

            ResultSet rs = ConnDB.search("select  invoice from prifixes where prifix_id='1' ");

            if (rs.next()) {
                String name = (rs.getString("invoice"));

                rs = ConnDB.search("select count(invoice_id) as x from invoice");
                if (rs.next()) {
                    int i = Integer.parseInt(rs.getString("x"));
                    i++;

                    if (i < 10) {
                        invoice_id_txt.setText(name + "000" + i);
                    } else if (i < 100) {

                        invoice_id_txt.setText(name + "00" + i);
                    } else if (i < 1000) {
                        invoice_id_txt.setText(name + "0" + i);
                    }

                    product_name_txt.grabFocus();
                }

            }
            mobile_txt.grabFocus();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        
    }
    
    
    public void calTot(){
        
         double qty1=0;
             double dis1=0;
             double net1=0;
             double gross=0;
             
     DefaultTableModel dtm=(DefaultTableModel)product_list_table.getModel();
        double tot=0;
        for(int i= 0;i<dtm.getRowCount();i++){
            String qty=dtm.getValueAt(i, 3).toString();
            String dis=dtm.getValueAt(i, 4).toString();
             String net=dtm.getValueAt(i, 5).toString();
           
             
              qty1+=Double.parseDouble(qty);
              discount1+=Double.parseDouble(dis);
              net1+=Double.parseDouble(net);
             gross=discount1+net1;
             
             
        }
        gross_amount_lbl.setText(gross+"");
        net_amount_lbl.setText(net1+"");
        item_count_lbl.setText(qty1+"");
        
    
    }

}
