/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UIL;

/**
 *
 * @author ASUS
 */
public class stock_adjustment extends javax.swing.JFrame {

    /**
     * Creates new form stock_adjustment
     */
    public stock_adjustment() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stock_count_id_txt = new javax.swing.JTextField();
        adj_id_txt = new javax.swing.JTextField();
        product_name_txt = new javax.swing.JTextField();
        date_txt = new javax.swing.JTextField();
        qty_txt = new javax.swing.JTextField();
        value_qty_txt = new javax.swing.JTextField();
        bt_complete_stock = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        stock_adj_close_btn = new javax.swing.JButton();
        search_stock_count_btn = new javax.swing.JButton();
        search_adj_id_btn = new javax.swing.JButton();
        adj_reason_cmb = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(300, 200, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Stock Count ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Adjustment ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Product Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Date :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Reason :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Quantity :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Total Value :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        stock_count_id_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        stock_count_id_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(stock_count_id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 230, 30));

        adj_id_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        adj_id_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(adj_id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 230, 30));

        product_name_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        product_name_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        product_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_name_txtActionPerformed(evt);
            }
        });
        jPanel1.add(product_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 230, 30));

        date_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        date_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 230, 30));

        qty_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        qty_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        qty_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty_txtActionPerformed(evt);
            }
        });
        jPanel1.add(qty_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 230, 30));

        value_qty_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        value_qty_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5)));
        jPanel1.add(value_qty_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 230, 30));

        bt_complete_stock.setBackground(new java.awt.Color(34, 155, 60));
        bt_complete_stock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_complete_stock.setForeground(new java.awt.Color(255, 255, 255));
        bt_complete_stock.setText("Complete");
        bt_complete_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_complete_stockActionPerformed(evt);
            }
        });
        jPanel1.add(bt_complete_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Stock Adjustment");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, 170, -1));

        stock_adj_close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sub_close_btn.png"))); // NOI18N
        stock_adj_close_btn.setContentAreaFilled(false);
        stock_adj_close_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sub_close_btn_hover.png"))); // NOI18N
        stock_adj_close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_adj_close_btnActionPerformed(evt);
            }
        });
        jPanel2.add(stock_adj_close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        search_stock_count_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        search_stock_count_btn.setContentAreaFilled(false);
        search_stock_count_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon_hover.png"))); // NOI18N
        jPanel1.add(search_stock_count_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 30, 30));

        search_adj_id_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        search_adj_id_btn.setContentAreaFilled(false);
        search_adj_id_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon_hover.png"))); // NOI18N
        jPanel1.add(search_adj_id_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 30, 30));

        adj_reason_cmb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        adj_reason_cmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(adj_reason_cmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 230, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void product_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_name_txtActionPerformed

    private void qty_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty_txtActionPerformed

    private void bt_complete_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_complete_stockActionPerformed
        

        String stockCountID= stock_count_id_txt.getText();
        String adjustmentID = adj_id_txt.getText();
        String productName = product_name_txt.getText();
        String date = date_txt.getText();
        String reason = adj_reason_cmb.getSelectedItem().toString();
        int quantity= Integer.parseInt(qty_txt.getText());
        int valueOfQuantity = Integer.parseInt(value_qty_txt.getText());
        
        if (stockCountID.isEmpty() || adjustmentID.isEmpty() || date.isEmpty() || date.isEmpty() || reason.isEmpty() || qty_txt.getText().isEmpty() || value_qty_txt.getText().isEmpty()){}
        




    }//GEN-LAST:event_bt_complete_stockActionPerformed

    private void stock_adj_close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_adj_close_btnActionPerformed
        
        this.dispose();
        System.gc();
        
    }//GEN-LAST:event_stock_adj_close_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock_adjustment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock_adjustment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock_adjustment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock_adjustment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock_adjustment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adj_id_txt;
    private javax.swing.JComboBox adj_reason_cmb;
    private javax.swing.JButton bt_complete_stock;
    private javax.swing.JTextField date_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField product_name_txt;
    private javax.swing.JTextField qty_txt;
    private javax.swing.JButton search_adj_id_btn;
    private javax.swing.JButton search_stock_count_btn;
    private javax.swing.JButton stock_adj_close_btn;
    private javax.swing.JTextField stock_count_id_txt;
    private javax.swing.JTextField value_qty_txt;
    // End of variables declaration//GEN-END:variables
}
